version: '3'
services:

  guacamole:
    container_name: 'guacamole'
    image: guacamole/guacamole:1.0.0
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: ${POSTGRES_DB:-guac_db}
      POSTGRES_USER: ${POSTGRES_USER:-guac_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-guac_db_password}
    depends_on:
      - postgres
      - guacd

  guacd:
    container_name: 'guacd'
    image: guacamole/guacd:1.0.0
    restart: unless-stopped

  postgres:
    container_name: 'postgres'
    build: .
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-guac_db}
      POSTGRES_USER: ${POSTGRES_USER:-guac_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-guac_db_password}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
